local S = minetest.get_translator("marinara")

minetest.register_node("marinara:hardcoral_brown", {
	description = S("Brown Hard Coral"),
	tiles = {"marinara_hardcoral_brown.png"},
	groups = {cracky = 3, stone = 1, coral = 1},
        light_source = 2,
	drop = "marinara:hardcoral_brown",
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("marinara:hardcoral", {
	description = S("Hard Coral"),
	tiles = {"marinara_hardcoral.png"},
	groups = {cracky = 3, stone = 1, coral = 1},
        light_source = 2,
	drop = "marinara:hardcoral",
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("marinara:hardcoral_blue", {
	description = S("Blue Hard Coral"),
	tiles = {"marinara_hardcoral_blue.png"},
	groups = {cracky = 3, stone = 1, coral = 1},
	drop = "marinara:hardcoral_blue",
        light_source = 2,
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("marinara:hardcoral_green", {
	description = S("Green Hard Coral"),
	tiles = {"marinara_hardcoral_green.png"},
	groups = {cracky = 3, stone = 1, coral = 1},
        light_source = 2,
	drop = "marinara:hardcoral_green",
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("marinara:hardcoral_pink", {
	description = S("Pink Hard Coral"),
	tiles = {"marinara_hardcoral_pink.png"},
	groups = {cracky = 3, stone = 1, coral = 1},
        light_source = 2,
	drop = "marinara:hardcoral_pink",
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("marinara:hardcoral_red", {
	description = S("Red Hard Coral"),
	tiles = {"marinara_hardcoral_red.png"},
	groups = {cracky = 3, stone = 1, coral = 1},
        light_source = 2,
	drop = "marinara:hardcoral_red",
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("marinara:hardcoral_violet", {
	description = S("Violet Hard Coral"),
	tiles = {"marinara_hardcoral_violet.png"},
	groups = {cracky = 3, stone = 1, coral = 1},
        light_source = 2,
	drop = "marinara:hardcoral_violet",
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("marinara:hardcoral_yellow", {
	description = S("Yellow Hard Coral"),
	tiles = {"marinara_hardcoral_yellow.png"},
	groups = {cracky = 3, stone = 1, coral = 1},
        light_source = 2,
	drop = "marinara:hardcoral_yellow",
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("marinara:coastrock", {
	description = S("Coastal Rock"),
	tiles = {"marinara_coastrock.png"},
	groups = {cracky = 3, stone = 1},
	drop = "marinara:coastrock",
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("marinara:coastrock_alage", {
	description = S("Coastal Rock with Alage"),
	tiles = {"marinara_coastrock_alage.png"},
	groups = {cracky = 3, stone = 1},
	drop = "marinara:coastrock_alage",
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})

minetest.register_node("marinara:seapocks", {
	description = S("Sea Pocks"),
	tiles = {"marinara_seapocks.png"},
	groups = {cracky = 3, stone = 1},
	drop = "marinara:seapocks",
	legacy_mineral = true,
	sounds = default.node_sound_stone_defaults(),
})